CREATE DATABASE groupomania CHARACTER SET 'utf8';
USE groupomania;

CREATE TABLE User (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    mail VARCHAR(30) NOT NULL,
    'password' VARCHAR(30), NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;

CREATE TABLE Post (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content TEXT,
    id_user SMALLINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_id
        FOREIGN KEY (idUser)
        REFERENCES User(id)
)
ENGINE=INNODB;

CREATE TABLE Comments (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content TEXT,
)
ENGINE=INNODB;

